name:                powerpants
version:             0.1.0.0
github:              "laserpants/powerpants"
license:             BSD3
author:              "laserpants"
maintainer:          "hildenjohannes@gmail.com"
copyright:           "2018 Johannes Hildén"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/laserpants/powerpants#readme>

dependencies:
- base >= 4.7 && < 5
- numeric-prelude
- unordered-containers

library:
  source-dirs: src

executables:
  powerpants-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powerpants

tests:
  powerpants-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powerpants
    - hspec
